# Generated by Django 6.0.6 on 2026-06-15 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping settings',
                'verbose_name_plural': 'Shipping settings',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('states', models.TextField(blank=True, help_text='Comma-separated state names (e.g. Maharashtra, Karnataka)')),
                ('pincode_prefixes', models.TextField(blank=True, help_text='Comma-separated pincode prefixes (e.g. 40, 41, 560)')),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use global flat rate', max_digits=10, null=True)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use global threshold', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
